'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Emma.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property assassinscreedii() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("assassinscreedii", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Leon est un navet
        '''Mais +u+ est quelqu&apos;un de tres chouette
        '''Et Blandine est jolie
        '''Dylan est un super poto
        '''+u+ est vraiment formidable
        '''Ma vie ne serait pas la meme sans +u+ &lt;3
        '''Je suis si heureux quand +u+ est heureux :-)
        '''+u+, c&apos;est vraiment un chouette prenom
        '''Va sortir t&apos;aerer, tu sera mieux qu&apos;ici ^^
        '''Va donc dire a quelqu&apos;un a quel point il est sympa ...
        '''I LOVE YOU
        '''J&apos;espere que tu passe un bon moment :-)
        '''Emma aime vraiment beaucoup les cochons. rrh rrh !.
        '''</summary>
        Friend ReadOnly Property Compliments() As String
            Get
                Return ResourceManager.GetString("Compliments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property emmaeclair() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("emmaeclair", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property flechebas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flechebas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fond() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fond", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à 000.
        '''</summary>
        Friend ReadOnly Property Level1() As String
            Get
                Return ResourceManager.GetString("Level1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MDLserverKO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MDLserverKO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MDLserverLinked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MDLserverLinked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MDLserverOK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MDLserverOK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à bleu
        '''super
        '''autre
        '''bizarre
        '''difficile
        '''drôle
        '''étrange
        '''facile
        '''grave
        '''impossible
        '''jeune
        '''juste
        '''libre
        '''malade
        '''même
        '''pauvre
        '''possible
        '''propre
        '''rouge
        '''sale
        '''simple
        '''tranquille
        '''triste
        '''vide
        '''bonne
        '''toute
        '''doux
        '''faux
        '''français
        '''gros
        '''heureux
        '''mauvais
        '''sérieux
        '''vieux
        '''vrai
        '''ancien
        '''beau
        '''blanc
        '''certain
        '''chaud
        '''cher
        '''clair
        '''content
        '''dernier
        '''désolé
        '''différent
        '''droit
        '''entier
        '''fort
        '''froid
        '''gentil
        '''grand
        '''haut
        '''humain
        '''important
        '''joli
        '''léger
        '''long
        '''meilleur
        '''mort
        '''noir
        '''nouveau
        '''pareil
        '''petit
        '''plein
        '''premier
        '''prê [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property MotsPendu() As String
            Get
                Return ResourceManager.GetString("MotsPendu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property smiley() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smiley", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
